
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Code generated by Microsoft (R) AutoRest Code Generator.Changes may cause incorrect behavior and will be lost if the code
# is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis
Sets the properties of a storage account’s Blob service, including properties for Storage Analytics and CORS (Cross-Origin Resource Sharing) rules.
.Description
Sets the properties of a storage account’s Blob service, including properties for Storage Analytics and CORS (Cross-Origin Resource Sharing) rules.
.Example
{{ Add code here }}
.Example
{{ Add code here }}

.Inputs
Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.Api20210801.IBlobServiceProperties
.Outputs
Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.Api20210801.IBlobServiceProperties
.Notes
COMPLEX PARAMETER PROPERTIES

To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.

BLOBSERVICEPROPERTY <IBlobServicePropertiesAutoGenerated>: The properties of a storage account’s Blob service.
  [AutomaticSnapshotPolicyEnabled <Boolean?>]: Deprecated in favor of isVersioningEnabled property.
  [ChangeFeedEnabled <Boolean?>]: Indicates whether change feed event logging is enabled for the Blob service.
  [ChangeFeedRetentionInDay <Int32?>]: Indicates the duration of changeFeed retention in days. Minimum value is 1 day and maximum value is 146000 days (400 years). A null value indicates an infinite retention of the change feed.
  [ContainerDeleteRetentionPolicyDay <Int32?>]: Indicates the number of days that the deleted item should be retained. The minimum specified value can be 1 and the maximum value can be 365.
  [ContainerDeleteRetentionPolicyEnabled <Boolean?>]: Indicates whether DeleteRetentionPolicy is enabled.
  [CorCorsRule <ICorsRule[]>]: The List of CORS rules. You can include up to five CorsRule elements in the request. 
    AllowedHeader <String[]>: Required if CorsRule element is present. A list of headers allowed to be part of the cross-origin request.
    AllowedMethod <String[]>: Required if CorsRule element is present. A list of HTTP methods that are allowed to be executed by the origin.
    AllowedOrigin <String[]>: Required if CorsRule element is present. A list of origin domains that will be allowed via CORS, or "*" to allow all domains
    ExposedHeader <String[]>: Required if CorsRule element is present. A list of response headers to expose to CORS clients.
    MaxAgeInSecond <Int32>: Required if CorsRule element is present. The number of seconds that the client/browser should cache a preflight response.
  [DefaultServiceVersion <String>]: DefaultServiceVersion indicates the default version to use for requests to the Blob service if an incoming request’s version is not specified. Possible values include version 2008-10-27 and all more recent versions.
  [DeleteRetentionPolicyDay <Int32?>]: Indicates the number of days that the deleted item should be retained. The minimum specified value can be 1 and the maximum value can be 365.
  [DeleteRetentionPolicyEnabled <Boolean?>]: Indicates whether DeleteRetentionPolicy is enabled.
  [IsVersioningEnabled <Boolean?>]: Versioning is enabled if set to true.
  [LastAccessTimeTrackingPolicyBlobType <String[]>]: An array of predefined supported blob types. Only blockBlob is the supported value. This field is currently read only
  [LastAccessTimeTrackingPolicyEnable <Boolean?>]: When set to true last access time based tracking is enabled.
  [LastAccessTimeTrackingPolicyName <Name?>]: Name of the policy. The valid value is AccessTimeTracking. This field is currently read only
  [LastAccessTimeTrackingPolicyTrackingGranularityInDay <Int32?>]: The field specifies blob object tracking granularity in days, typically how often the blob object should be tracked.This field is currently read only with value as 1
  [RestorePolicyDay <Int32?>]: how long this blob can be restored. It should be great than zero and less than DeleteRetentionPolicy.days.
  [RestorePolicyEnabled <Boolean?>]: Blob restore is enabled if set to true.

PARAMETER <IBlobServiceProperties>: The properties of a storage account’s Blob service.
  [BlobServiceProperty <IBlobServicePropertiesAutoGenerated>]: The properties of a storage account’s Blob service.
    [AutomaticSnapshotPolicyEnabled <Boolean?>]: Deprecated in favor of isVersioningEnabled property.
    [ChangeFeedEnabled <Boolean?>]: Indicates whether change feed event logging is enabled for the Blob service.
    [ChangeFeedRetentionInDay <Int32?>]: Indicates the duration of changeFeed retention in days. Minimum value is 1 day and maximum value is 146000 days (400 years). A null value indicates an infinite retention of the change feed.
    [ContainerDeleteRetentionPolicyDay <Int32?>]: Indicates the number of days that the deleted item should be retained. The minimum specified value can be 1 and the maximum value can be 365.
    [ContainerDeleteRetentionPolicyEnabled <Boolean?>]: Indicates whether DeleteRetentionPolicy is enabled.
    [CorCorsRule <ICorsRule[]>]: The List of CORS rules. You can include up to five CorsRule elements in the request. 
      AllowedHeader <String[]>: Required if CorsRule element is present. A list of headers allowed to be part of the cross-origin request.
      AllowedMethod <String[]>: Required if CorsRule element is present. A list of HTTP methods that are allowed to be executed by the origin.
      AllowedOrigin <String[]>: Required if CorsRule element is present. A list of origin domains that will be allowed via CORS, or "*" to allow all domains
      ExposedHeader <String[]>: Required if CorsRule element is present. A list of response headers to expose to CORS clients.
      MaxAgeInSecond <Int32>: Required if CorsRule element is present. The number of seconds that the client/browser should cache a preflight response.
    [DefaultServiceVersion <String>]: DefaultServiceVersion indicates the default version to use for requests to the Blob service if an incoming request’s version is not specified. Possible values include version 2008-10-27 and all more recent versions.
    [DeleteRetentionPolicyDay <Int32?>]: Indicates the number of days that the deleted item should be retained. The minimum specified value can be 1 and the maximum value can be 365.
    [DeleteRetentionPolicyEnabled <Boolean?>]: Indicates whether DeleteRetentionPolicy is enabled.
    [IsVersioningEnabled <Boolean?>]: Versioning is enabled if set to true.
    [LastAccessTimeTrackingPolicyBlobType <String[]>]: An array of predefined supported blob types. Only blockBlob is the supported value. This field is currently read only
    [LastAccessTimeTrackingPolicyEnable <Boolean?>]: When set to true last access time based tracking is enabled.
    [LastAccessTimeTrackingPolicyName <Name?>]: Name of the policy. The valid value is AccessTimeTracking. This field is currently read only
    [LastAccessTimeTrackingPolicyTrackingGranularityInDay <Int32?>]: The field specifies blob object tracking granularity in days, typically how often the blob object should be tracked.This field is currently read only with value as 1
    [RestorePolicyDay <Int32?>]: how long this blob can be restored. It should be great than zero and less than DeleteRetentionPolicy.days.
    [RestorePolicyEnabled <Boolean?>]: Blob restore is enabled if set to true.
  [SkuName <SkuName?>]: The SKU name. Required for account creation; optional for update. Note that in older versions, SKU name was called accountType.
  [SkuTier <SkuTier?>]: The SKU tier. This is based on the SKU name.
.Link
https://docs.microsoft.com/powershell/module/az.storage/set-azstorageblobserviceproperty
#>
function Set-AzStorageBlobServiceProperty {
[OutputType([Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.Api20210801.IBlobServiceProperties])]
[CmdletBinding(DefaultParameterSetName='SetExpanded', PositionalBinding=$false, SupportsShouldProcess, ConfirmImpact='Medium')]
param(
    [Parameter(Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Category('Path')]
    [System.String]
    # The name of the storage account within the specified resource group.
    # Storage account names must be between 3 and 24 characters in length and use numbers and lower-case letters only.
    ${AccountName},

    [Parameter(Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Category('Path')]
    [System.String]
    # The name of the resource group within the user's subscription.
    # The name is case insensitive.
    ${ResourceGroupName},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Category('Path')]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Runtime.DefaultInfo(Script='(Get-AzContext).Subscription.Id')]
    [System.String]
    # The ID of the target subscription.
    ${SubscriptionId},

    [Parameter(ParameterSetName='Set', Mandatory, ValueFromPipeline)]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Category('Body')]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.Api20210801.IBlobServiceProperties]
    # The properties of a storage account’s Blob service.
    # To construct, see NOTES section for PARAMETER properties and create a hash table.
    ${Parameter},

    [Parameter(ParameterSetName='SetExpanded')]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Category('Body')]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Models.Api20210801.IBlobServicePropertiesAutoGenerated]
    # The properties of a storage account’s Blob service.
    # To construct, see NOTES section for BLOBSERVICEPROPERTY properties and create a hash table.
    ${BlobServiceProperty},

    [Parameter()]
    [Alias('AzureRMContext', 'AzureCredential')]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Category('Azure')]
    [System.Management.Automation.PSObject]
    # The credentials, account, tenant, and subscription used for communication with Azure.
    ${DefaultProfile},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Wait for .NET debugger to attach
    ${Break},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be appended to the front of the pipeline
    ${HttpPipelineAppend},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Category('Runtime')]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Runtime.SendAsyncStep[]]
    # SendAsync Pipeline Steps to be prepended to the front of the pipeline
    ${HttpPipelinePrepend},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Category('Runtime')]
    [System.Uri]
    # The URI for the proxy server to use
    ${Proxy},

    [Parameter(DontShow)]
    [ValidateNotNull()]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Category('Runtime')]
    [System.Management.Automation.PSCredential]
    # Credentials for a proxy server to use for the remote call
    ${ProxyCredential},

    [Parameter(DontShow)]
    [Microsoft.Azure.PowerShell.Cmdlets.Storage.Category('Runtime')]
    [System.Management.Automation.SwitchParameter]
    # Use the default credentials for the proxy
    ${ProxyUseDefaultCredentials}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName
        $mapping = @{
            Set = 'Az.Storage.private\Set-AzStorageBlobServiceProperty_Set';
            SetExpanded = 'Az.Storage.private\Set-AzStorageBlobServiceProperty_SetExpanded';
        }
        if (('Set', 'SetExpanded') -contains $parameterSet -and -not $PSBoundParameters.ContainsKey('SubscriptionId')) {
            $PSBoundParameters['SubscriptionId'] = (Get-AzContext).Subscription.Id
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [Microsoft.Azure.PowerShell.Cmdlets.Storage.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {
        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {
        throw
    }
}

end {
    try {
        $steppablePipeline.End()
    } catch {
        throw
    }
}
}
